print('Hello World!')
name = input("What's is your name? ")
age = int(input(f'How old are you {name}? '))
print(f'Name: {name}, Age:{age} years old')
print("Congratulations! You've done your registration!")
